### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by fooflare** [choptastic/sigma_sql#2]
Hi Jesse,

I am not sure if this project is frozen or if you are working/using it right now, but I think it is interesting for making a middle layer between applications and database drivers. Today I am making some tests with nitrogen and users login and I realized that the transactions would be very interesting. What do you think about it?

Thank you.

**Comment by choptastic** [comment]
Transactions are added in the current 'alias' branch (https://github.com/choptastic/sigma_sql/tree/alias), which will be merged into master soon (next day or two). Closing this issue.
